### ISSUE TITLE
arm package on Mac

### ISSUE THREAD

**Issue by afbroman** [johnmyleswhite/ML_for_Hackers#1]
Are there any known issues in using the arm package on Mac? 

On running package_installer.R, there were errors in compiling BRugs, which isn't a direct dependency of the arm package, but is suggested for R2WinBUGS, which is.

Are there issues in running any of the book's code on Mac, if it's depending on OpenBUGS and WinBUGS, which seem to be Windows-specific libraries? Or are these libraries never used?

**Comment by johnmyleswhite** [comment]
The 'arm' package is probably never used. I will look into it. Both Drew and I run the code on OS X.

 -- John

**Comment by johnmyleswhite** [comment]
I found no evidence that `arm` was ever used, so I've removed it from the `package_installer.R` script.
