### ISSUE TITLE
Ch. 11 Social Network Data

### ISSUE THREAD

**Issue by BKJackson** [johnmyleswhite/ML_for_Hackers#12]
Since the Google Social Graph API is not longer available, can you recommend any other currently active sources of data for 'practicing' the network analysis methods discussed in Chapter 11? 

Thanks.

**Comment by johnmyleswhite** [comment]
Here you go: http://snap.stanford.edu/data/

**Comment by BKJackson** [comment]
Omagoodness. That's a lot of data. Thanks.
