### ISSUE TITLE
Weak

### ISSUE THREAD

**Issue by obscaenvs** [johnmyleswhite/ML_for_Hackers#18]
It is really weak that the repository does not have the source code that is the one talked about in the book. Instead of actually learning when working through examples, I have to sit down and search your repository for definitions that have changed (e.g. 'abb.state' in Chapter 1). Just mindnumbingly weak.

**Comment by johnmyleswhite** [comment]
Thankfully, the existence of version control resolves some of this issue: https://github.com/johnmyleswhite/ML_for_Hackers/tree/9fa3c62ef465f6386cc786ba7cebdb26bf362c97

Unfortunately, the book shipped with several errors that the online code fixed. In addition, the API's used by the book were deprecated after publication, requiring the most recent rounds of revisions.

Please use a more informative issue title in the future.
