### ISSUE TITLE
no hard_ham_2 from spamassassin?

### ISSUE THREAD

**Issue by ajschumacher** [johnmyleswhite/ML_for_Hackers#21]
Hi! Looking at @drewconway's [email_classify.R](https://github.com/johnmyleswhite/ML_for_Hackers/blob/master/03-Classification/email_classify.R), I follow the reference to http://spamassassin.apache.org/publiccorpus/ to find the data, but there doesn't seem to be a hard_ham_2 anywhere. Is there hard_ham_2?

**Comment by johnmyleswhite** [comment]
I think the data's here: https://github.com/johnmyleswhite/ML_for_Hackers/tree/master/03-Classification/data

**Comment by ajschumacher** [comment]
Thanks! I had been trying to get it all from spamassassin.apache.org, but that'll do fine! :)
