### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by vicforu** [johnmyleswhite/ML_for_Hackers#34]
How can i get the data used in this book?

**Comment by chaitrakamath** [comment]
For each chapter, go to that chapter's folder. For example, if you are looking for data of Ch03. Follow this link:
https://github.com/johnmyleswhite/ML_for_Hackers/tree/master/03-Classification

You would see 'data' folder there. Click the data folder and click the file you want to download. Then, on top right, click 'Raw' button. This would give you the data. Use Ctrl + S (for Windows) or Command + S (for mac) and save the data to a folder on your machine. 

Hope this helps,

Best, 
Chai

**Comment by stevewyl** [comment]
Thank you ！！

**Comment by pokiller99** [comment]
Thank you,too. It's cool!~lol

stevewyl notifications@github.com 於 2016年1月3日星期日 寫道：

> Thank you ！！
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/johnmyleswhite/ML_for_Hackers/issues/34#issuecomment-168494690
> .

## 

---

公司:創越數位行銷公司
姓名:林威成
職位:遊戲市場數據分析師
e-mail: M0216378@mail.fcu.edu.tw

---
